import { env } from "@env/client.mjs";

export const mapStyle = {
  version: 8,
  name: "NLS Basemap",
  metadata: { "maputnik:renderer": "mbgljs" },
  center: [21.645, 63.101],
  zoom: 11.35,
  sources: {
    taustakartta: {
      type: "vector",
      url: `https://avoin-karttakuva.maanmittauslaitos.fi/vectortiles/tilejson/taustakartta/1.0.0/taustakartta/default/v20/WGS84_Pseudo-Mercator/tilejson.json?api-key=${env.NEXT_PUBLIC_MML_API_KEY}`,
    },
  },
  glyphs: `https://avoin-karttakuva.maanmittauslaitos.fi/vectortiles/glyphs/{fontstack}/{range}.pbf?api-key=${env.NEXT_PUBLIC_MML_API_KEY}`,
  layers: [
    {
      id: "background",
      type: "background",
      paint: { "background-color": "rgba(15, 23, 42, 1)" },
    },
    {
      id: "hallintoalue",
      type: "line",
      source: "taustakartta",
      "source-layer": "hallintoalue",
      layout: { visibility: "visible" },
      paint: { "line-color": "rgba(129, 188, 255, 1)", "line-width": 1 },
    },
    {
      id: "vesisto_alue",
      type: "line",
      source: "taustakartta",
      "source-layer": "vesisto_alue",
      layout: { visibility: "visible" },
      paint: { "line-color": "rgba(129, 188, 255, 0.5)", "line-width": 2 },
    },
    {
      id: "vesisto_alue_fill",
      type: "fill",
      source: "taustakartta",
      "source-layer": "vesisto_alue",
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgba(6, 15, 24, 1)" },
    },
    {
      id: "liikenne_viiva",
      type: "line",
      source: "taustakartta",
      "source-layer": "liikenne",
      filter: ["==", ["geometry-type"], "LineString"],
      layout: { visibility: "visible" },
      paint: { "line-color": "rgba(49, 95, 152, 1)", "line-width": 1 },
    },
    {
      id: "rakennus",
      type: "fill",
      source: "taustakartta",
      "source-layer": "rakennus",
      layout: { visibility: "visible" },
      paint: {
        "fill-color": "rgba(16, 40, 63, 1)",
        "fill-antialias": false,
        "fill-opacity": 0.5,
      },
    },
    {
      id: "nimisto",
      type: "symbol",
      source: "taustakartta",
      "source-layer": "nimisto",
      filter: [
        "all",
        ["!", ["match", ["get", "teema"], ["Maasto", "Vedet"], true, false]],
        ["!=", ["get", "alaryhma"], "Hallintoalueet"],
        [
          "match",
          ["get", "laji"],
          ["Kansallispuisto", "Luonnonpuisto"],
          false,
          true,
        ],
      ],
      layout: {
        "text-transform": [
          "match",
          ["get", "alaryhma"],
          "Rautatieliikennepaikat",
          "uppercase",
          "none",
        ],
        "text-field": [
          "coalesce",
          ["get", "nimi_fin"],
          ["get", "nimi_swe"],
          ["get", "nimi_sme"],
          ["get", "nimi_sms"],
          ["get", "nimi_smn"],
        ],
        "icon-ignore-placement": true,
        "icon-allow-overlap": true,
        "text-font": ["Liberation Sans NLSFI"],
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          1,
          ["interpolate", ["linear"], ["get", "prioriteetti"], 1, 20, 3, 16],
          10,
          ["interpolate", ["linear"], ["get", "prioriteetti"], 5, 16, 7, 13],
          14,
          ["interpolate", ["linear"], ["get", "prioriteetti"], 5, 22, 10, 12],
        ],
        visibility: "visible",
      },
      paint: {
        "text-halo-color": "rgba(9, 22, 36, 1)",
        "text-color": "rgba(255, 255, 255, 1)",
        "text-halo-blur": 1,
        "text-halo-width": 2,
        "text-opacity": 0.6,
      },
    },
  ],
  id: "o32dezi2d",
};
